/*
 * Copyright (c) 2020.  Zenex.Tech@ https://zenex.tech
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.javed.phonenumberinput;

import java.util.ArrayList;
import java.util.List;

public class Countries {

    public static final List<Country> COUNTRIES=new ArrayList<>();

    static {
        COUNTRIES.add(new Country("Afghanistan","AF","93","afghanistan"));
        COUNTRIES.add(new Country("Albania","AL","355","albania"));
        COUNTRIES.add(new Country("Algeria","DZ","213","algeria"));
        COUNTRIES.add(new Country("Andorra","AD","376","andorra"));
        COUNTRIES.add(new Country("Angola","AO","244","angola"));
        COUNTRIES.add(new Country("Antigua and Barbuda","AG","1268","antigua-and-barbuda"));
        COUNTRIES.add(new Country("Argentina","AR","54","argentina"));
        COUNTRIES.add(new Country("Armenia","AM","374","armenia"));
        COUNTRIES.add(new Country("Australia","AU","61","australia"));
        COUNTRIES.add(new Country("Austria","AT","43","austria"));
        COUNTRIES.add(new Country("Azerbaijan","AZ","994","azerbaijan"));
        COUNTRIES.add(new Country("Bahamas","BS","1242","bahamas"));
        COUNTRIES.add(new Country("Bahrain","BH","973","bahrain"));
        COUNTRIES.add(new Country("Bangladesh","BD","880","bangladesh"));
        COUNTRIES.add(new Country("Barbados","BB","1246","barbados"));
        COUNTRIES.add(new Country("Belarus","BY","375","belarus"));
        COUNTRIES.add(new Country("Belgium","BE","32","belgium"));
        COUNTRIES.add(new Country("Belize","BZ","501","belize"));
        COUNTRIES.add(new Country("Benin","BJ","229","benin"));
        COUNTRIES.add(new Country("Bhutan","BT","975","bhutan"));
        COUNTRIES.add(new Country("Bolivia","BO","591","bolivia"));
        COUNTRIES.add(new Country("Bosnia and Herzegovina","BA","387","bosnia-and-herzegovina"));
        COUNTRIES.add(new Country("Botswana","BW","267","botswana"));
        COUNTRIES.add(new Country("Brazil","BR","55","brazil"));
        COUNTRIES.add(new Country("Brunei","BN","673","brunei"));
        COUNTRIES.add(new Country("Bulgaria","BG","359","bulgaria"));
        COUNTRIES.add(new Country("Burkina Faso","BF","226","burkina-faso"));
        COUNTRIES.add(new Country("Burundi","BI","257","burundi"));
        COUNTRIES.add(new Country("Cambodia","KH","855","cambodia"));
        COUNTRIES.add(new Country("Cameroon","CM","237","cameroon"));
        COUNTRIES.add(new Country("Canada","CA","1","canada"));
        COUNTRIES.add(new Country("Cape Verde","CV","238","cape-verde"));
        COUNTRIES.add(new Country("Central African Republic","CF","236","central-african-republic"));
        COUNTRIES.add(new Country("Chad","TD","235","chad"));
        COUNTRIES.add(new Country("Chile","CL","56","chile"));
        COUNTRIES.add(new Country("China","CN","86","china"));
        COUNTRIES.add(new Country("Colombia","CO","57","colombia"));
        COUNTRIES.add(new Country("Comoros","KM","269","comoros"));
        COUNTRIES.add(new Country("Costa Rica","CR","506","costa-rica"));
        COUNTRIES.add(new Country("Croatia","HR","385","croatia"));
        COUNTRIES.add(new Country("Cuba","CU","53","cuba"));
        COUNTRIES.add(new Country("Cyprus","CY","357","cyprus"));
        COUNTRIES.add(new Country("Czech Republic","CZ","420","czech-republic"));
        COUNTRIES.add(new Country("Democratic Republic of the Congo","CD","243","democratic-republic-of-congo"));
        COUNTRIES.add(new Country("Denmark","DK","45","denmark"));
        COUNTRIES.add(new Country("Djibouti","DJ","253","djibouti"));
        COUNTRIES.add(new Country("Dominica","DM","1767","dominica"));
        COUNTRIES.add(new Country("Dominican Republic","DO","1","dominican-republic"));
        COUNTRIES.add(new Country("East Timor","TL","670","east-timor"));
        COUNTRIES.add(new Country("Ecuador","EC","593","ecuador"));
        COUNTRIES.add(new Country("Egypt","EG","20","egypt"));
        COUNTRIES.add(new Country("El Salvador","SV","503","salvador"));
        COUNTRIES.add(new Country("Equatorial Guinea","GQ","240","equatorial-guinea"));
        COUNTRIES.add(new Country("Eritrea","ER","291","eritrea"));
        COUNTRIES.add(new Country("Estonia","EE","372","estonia"));
        COUNTRIES.add(new Country("Ethiopia","ET","251","ethiopia"));
        COUNTRIES.add(new Country("Fiji","FJ","679","fiji"));
        COUNTRIES.add(new Country("Finland","FI","358","finland"));
        COUNTRIES.add(new Country("France","FR","33","france"));
        COUNTRIES.add(new Country("Gabon","GA","241","gabon"));
        COUNTRIES.add(new Country("Gambia","GM","220","gambia"));
        COUNTRIES.add(new Country("Georgia","GE","995","georgia"));
        COUNTRIES.add(new Country("Germany","DE","49","germany"));
        COUNTRIES.add(new Country("Ghana","GH","233","ghana"));
        COUNTRIES.add(new Country("Greece","GR","30","greece"));
        COUNTRIES.add(new Country("Grenada","GD","1473","grenada"));
        COUNTRIES.add(new Country("Guatemala","GT","502","guatemala"));
        COUNTRIES.add(new Country("Guinea","GN","224","guinea"));
        COUNTRIES.add(new Country("Guinea-Bissau","GW","245","guinea-bissau"));
        COUNTRIES.add(new Country("Guyana","GY","592","guyana"));
        COUNTRIES.add(new Country("Haiti","HT","509","haiti"));
        COUNTRIES.add(new Country("Honduras","HN","504","honduras"));
        COUNTRIES.add(new Country("Hungary","HU","36","hungary"));
        COUNTRIES.add(new Country("Iceland","IS","354","iceland"));
        COUNTRIES.add(new Country("India","IN","91","india"));
        COUNTRIES.add(new Country("Indonesia","ID","62","indonesia"));
        COUNTRIES.add(new Country("Iran","IR","98","iran"));
        COUNTRIES.add(new Country("Iraq","IQ","964","iraq"));
        COUNTRIES.add(new Country("Ireland","IE","353","ireland"));
        COUNTRIES.add(new Country("Israel","IL","972","israel"));
        COUNTRIES.add(new Country("Italy","IT","39","italy"));
        COUNTRIES.add(new Country("Ivory Coast","CI","225","ivory-coast"));
        COUNTRIES.add(new Country("Jamaica","JM","1876","jamaica"));
        COUNTRIES.add(new Country("Japan","JP","81","japan"));
        COUNTRIES.add(new Country("Jordan","JO","962","jordan"));
        COUNTRIES.add(new Country("Kazakhstan","KZ","7","kazakhstan"));
        COUNTRIES.add(new Country("Kenya","KE","254","kenya"));
        COUNTRIES.add(new Country("Kiribati","KI","686","kiribati"));
        COUNTRIES.add(new Country("Kuwait","KW","965","kuwait"));
        COUNTRIES.add(new Country("Kyrgyzstan","KG","996","kyrgyzstan"));
        COUNTRIES.add(new Country("Laos","LA","856","laos"));
        COUNTRIES.add(new Country("Latvia","LV","371","latvia"));
        COUNTRIES.add(new Country("Lebanon","LB","961","lebanon"));
        COUNTRIES.add(new Country("Lesotho","LS","266","lesotho"));
        COUNTRIES.add(new Country("Liberia","LR","231","liberia"));
        COUNTRIES.add(new Country("Libya","LY","218","libya"));
        COUNTRIES.add(new Country("Liechtenstein","LI","423","liechtenstein"));
        COUNTRIES.add(new Country("Lithuania","LT","370","lithuania"));
        COUNTRIES.add(new Country("Luxembourg","LU","352","luxembourg"));
        COUNTRIES.add(new Country("Macedonia","MK","389","republic-of-macedonia"));
        COUNTRIES.add(new Country("Madagascar","MG","261","madagascar"));
        COUNTRIES.add(new Country("Malawi","MW","265","malawi"));
        COUNTRIES.add(new Country("Malaysia","MY","60","malaysia"));
        COUNTRIES.add(new Country("Maldives","MV","960","maldives"));
        COUNTRIES.add(new Country("Mali","ML","223","mali"));
        COUNTRIES.add(new Country("Malta","MT","356","malta"));
        COUNTRIES.add(new Country("Marshall Islands","MH","692","marshall-island"));
        COUNTRIES.add(new Country("Mauritania","MR","222","mauritania"));
        COUNTRIES.add(new Country("Mauritius","MU","230","mauritius"));
        COUNTRIES.add(new Country("Mexico","MX","52","mexico"));
        COUNTRIES.add(new Country("Micronesia","FM","691","micronesia"));
        COUNTRIES.add(new Country("Moldova","MD","373","moldova"));
        COUNTRIES.add(new Country("Monaco","MC","377","monaco"));
        COUNTRIES.add(new Country("Mongolia","MN","976","mongolia"));
        COUNTRIES.add(new Country("Montenegro","ME","382","montenegro"));
        COUNTRIES.add(new Country("Morocco","MA","212","morocco"));
        COUNTRIES.add(new Country("Mozambique","MZ","258","mozambique"));
        COUNTRIES.add(new Country("Myanmar","MM","95","myanmar"));
        COUNTRIES.add(new Country("Namibia","","264","namibia"));
        COUNTRIES.add(new Country("Nauru","NR","674","nauru"));
        COUNTRIES.add(new Country("Nepal","NP","977","nepal"));
        COUNTRIES.add(new Country("Netherlands","NL","31","netherlands"));
        COUNTRIES.add(new Country("New Zealand","NZ","64","new-zealand"));
        COUNTRIES.add(new Country("Nicaragua","NI","505","nicaragua"));
        COUNTRIES.add(new Country("Niger","NE","227","niger"));
        COUNTRIES.add(new Country("Nigeria","NG","234","nigeria"));
        COUNTRIES.add(new Country("North Korea","KP","850","north-korea"));
        COUNTRIES.add(new Country("Norway","NO","47","norway"));
        COUNTRIES.add(new Country("Oman","OM","968","oman"));
        COUNTRIES.add(new Country("Pakistan","PK","92","pakistan"));
        COUNTRIES.add(new Country("Palau","PW","680","palau"));
        COUNTRIES.add(new Country("Palestine","PS","970","palestine"));
        COUNTRIES.add(new Country("Panama","PA","507","panama"));
        COUNTRIES.add(new Country("Papua New Guinea","PG","675","papua-new-guinea"));
        COUNTRIES.add(new Country("Paraguay","PY","595","paraguay"));
        COUNTRIES.add(new Country("Peru","PE","51","peru"));
        COUNTRIES.add(new Country("Philippines","PH","63","philippines"));
        COUNTRIES.add(new Country("Poland","PL","48","republic-of-poland"));
        COUNTRIES.add(new Country("Portugal","PT","351","portugal"));
        COUNTRIES.add(new Country("Qatar","QA","974","qatar"));
        COUNTRIES.add(new Country("Republic of the Congo","CG","242","republic-of-the-congo"));
        COUNTRIES.add(new Country("Romania","RO","40","romania"));
        COUNTRIES.add(new Country("Russia","RU","7","russia"));
        COUNTRIES.add(new Country("Rwanda","RW","250","rwanda"));
        COUNTRIES.add(new Country("Saint Kitts and Nevis","KN","1869","saint-kitts-and-nevis"));
        COUNTRIES.add(new Country("Saint Lucia","LC","1758","st-lucia"));
        COUNTRIES.add(new Country("Saint Vincent and the Grenadines","VC","1784","st-vincent-and-the-grenadines"));
        COUNTRIES.add(new Country("Samoa","WS","685","samoa"));
        COUNTRIES.add(new Country("San Marino","SM","378","san-marino"));
        COUNTRIES.add(new Country("Sao Tome and Principe","ST","239","sao-tome-and-principe"));
        COUNTRIES.add(new Country("Saudi Arabia","SA","966","saudi-arabia"));
        COUNTRIES.add(new Country("Senegal","SN","221","senegal"));
        COUNTRIES.add(new Country("Serbia","RS","381","serbia"));
        COUNTRIES.add(new Country("Seychelles","SC","248","seychelles"));
        COUNTRIES.add(new Country("Sierra Leone","SL","232","sierra-leone"));
        COUNTRIES.add(new Country("Singapore","SG","65","singapore"));
        COUNTRIES.add(new Country("Slovakia","SK","421","slovakia"));
        COUNTRIES.add(new Country("Slovenia","SI","386","slovenia"));
        COUNTRIES.add(new Country("Solomon Islands","SB","677","solomon-islands"));
        COUNTRIES.add(new Country("Somalia","SO","252","somalia"));
        COUNTRIES.add(new Country("South Africa","ZA","27","south-africa"));
        COUNTRIES.add(new Country("South Korea","KR","82","south-korea"));
        COUNTRIES.add(new Country("South Sudan","SS","211","south-sudan"));
        COUNTRIES.add(new Country("Spain","ES","34","spain"));
        COUNTRIES.add(new Country("Sri Lanka","LK","94","sri-lanka"));
        COUNTRIES.add(new Country("Sudan","SD","249","sudan"));
        COUNTRIES.add(new Country("Suriname","SR","597","suriname"));
        COUNTRIES.add(new Country("Swaziland","SZ","268","swaziland"));
        COUNTRIES.add(new Country("Sweden","SE","46","sweden"));
        COUNTRIES.add(new Country("Switzerland","CH","41","switzerland"));
        COUNTRIES.add(new Country("Syria","SY","963","syria"));
        COUNTRIES.add(new Country("Tajikistan","TJ","992","tajikistan"));
        COUNTRIES.add(new Country("Tanzania","TZ","255","tanzania"));
        COUNTRIES.add(new Country("Thailand","TH","66","thailand"));
        COUNTRIES.add(new Country("Togo","TG","228","togo"));
        COUNTRIES.add(new Country("Tonga","TO","676","tonga"));
        COUNTRIES.add(new Country("Trinidad and Tobago","TT","1868","trinidad-and-tobago"));
        COUNTRIES.add(new Country("Tunisia","TN","216","tunisia"));
        COUNTRIES.add(new Country("Turkey","TR","90","turkey"));
        COUNTRIES.add(new Country("Turkmenistan","TM","993","turkmenistan"));
        COUNTRIES.add(new Country("Tuvalu","TV","688","tuvalu"));
        COUNTRIES.add(new Country("Uganda","UG","256","uganda"));
        COUNTRIES.add(new Country("Ukraine","UA","380","ukraine"));
        COUNTRIES.add(new Country("United Arab Emirates","AE","971","united-arab-emirates"));
        COUNTRIES.add(new Country("United Kingdom","GB","44","united-kingdom"));
        COUNTRIES.add(new Country("United States","US","1","united-states-of-america"));
        COUNTRIES.add(new Country("Uruguay","UY","598","uruguay"));
        COUNTRIES.add(new Country("Uzbekistan","UZ","998","uzbekistn"));
        COUNTRIES.add(new Country("Vanuatu","VU","678","vanuatu"));
        COUNTRIES.add(new Country("Vatican","VA","379","vatican-city"));
        COUNTRIES.add(new Country("Venezuela","VE","58","venezuela"));
        COUNTRIES.add(new Country("Vietnam","VN","84","vietnam"));
        COUNTRIES.add(new Country("Yemen","YE","967","yemen"));
        COUNTRIES.add(new Country("Zambia","ZM","260","zambia"));
        COUNTRIES.add(new Country("Zimbabwe","ZW","263","zimbabwe"));
    }
}
